/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiTeamsCreateModel } from '../../models/api-teams-create-model';
import { apiTeamsOutputModel } from '../../models/api-teams-output-model';

export interface CreateTeamTeamsPost$Params {
      body: apiTeamsCreateModel
}

export function createTeamTeamsPost(http: HttpClient, rootUrl: string, params: CreateTeamTeamsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiTeamsOutputModel>> {
  const rb = new RequestBuilder(rootUrl, createTeamTeamsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiTeamsOutputModel>;
    })
  );
}

createTeamTeamsPost.PATH = '/teams/';
