/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteTeamTeamsTeamIdDelete$Params {
  team_id: string;
}

export function deleteTeamTeamsTeamIdDelete(http: HttpClient, rootUrl: string, params: DeleteTeamTeamsTeamIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, deleteTeamTeamsTeamIdDelete.PATH, 'delete');
  if (params) {
    rb.path('team_id', params.team_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

deleteTeamTeamsTeamIdDelete.PATH = '/teams/{team_id}';
