/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiTeamsOutputDetailModel } from '../../models/api-teams-output-detail-model';

export interface GetTeamsTeamsGet$Params {
  event_short_name: string;
}

export function getTeamsTeamsGet(http: HttpClient, rootUrl: string, params: GetTeamsTeamsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiTeamsOutputDetailModel>>> {
  const rb = new RequestBuilder(rootUrl, getTeamsTeamsGet.PATH, 'get');
  if (params) {
    rb.query('event_short_name', params.event_short_name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiTeamsOutputDetailModel>>;
    })
  );
}

getTeamsTeamsGet.PATH = '/teams/';
