/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetTeamEmailsTeamsEmailsGet$Params {
  event_short_name: string;
}

export function getTeamEmailsTeamsEmailsGet(http: HttpClient, rootUrl: string, params: GetTeamEmailsTeamsEmailsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, getTeamEmailsTeamsEmailsGet.PATH, 'get');
  if (params) {
    rb.query('event_short_name', params.event_short_name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

getTeamEmailsTeamsEmailsGet.PATH = '/teams/emails';
