/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiWaiverLinkModel } from '../../models/api-waiver-link-model';

export interface GetTeamWaiverLinksTeamsWaiverLinksGet$Params {
  team_name: string;
  event_short_name: string;
}

export function getTeamWaiverLinksTeamsWaiverLinksGet(http: HttpClient, rootUrl: string, params: GetTeamWaiverLinksTeamsWaiverLinksGet$Params, context?: HttpContext): Observable<StrictHttpResponse<(Array<apiWaiverLinkModel> | null)>> {
  const rb = new RequestBuilder(rootUrl, getTeamWaiverLinksTeamsWaiverLinksGet.PATH, 'get');
  if (params) {
    rb.query('team_name', params.team_name, {});
    rb.query('event_short_name', params.event_short_name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(Array<apiWaiverLinkModel> | null)>;
    })
  );
}

getTeamWaiverLinksTeamsWaiverLinksGet.PATH = '/teams/waiver-links';
