/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiTeamsOutputDetailModel } from '../../models/api-teams-output-detail-model';

export interface GetTeamInfoTeamsTeamIdGet$Params {
  team_id: string;
}

export function getTeamInfoTeamsTeamIdGet(http: HttpClient, rootUrl: string, params: GetTeamInfoTeamsTeamIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiTeamsOutputDetailModel>> {
  const rb = new RequestBuilder(rootUrl, getTeamInfoTeamsTeamIdGet.PATH, 'get');
  if (params) {
    rb.path('team_id', params.team_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiTeamsOutputDetailModel>;
    })
  );
}

getTeamInfoTeamsTeamIdGet.PATH = '/teams/{team_id}';
