/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiTeamsOutputModel } from '../../models/api-teams-output-model';
import { apiTeamsUpdateModel } from '../../models/api-teams-update-model';

export interface UpdateTeamTeamsTeamIdPatch$Params {
  team_id: string;
      body: apiTeamsUpdateModel
}

export function updateTeamTeamsTeamIdPatch(http: HttpClient, rootUrl: string, params: UpdateTeamTeamsTeamIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiTeamsOutputModel>> {
  const rb = new RequestBuilder(rootUrl, updateTeamTeamsTeamIdPatch.PATH, 'patch');
  if (params) {
    rb.path('team_id', params.team_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiTeamsOutputModel>;
    })
  );
}

updateTeamTeamsTeamIdPatch.PATH = '/teams/{team_id}';
