/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiBearerResponse } from '../../models/api-bearer-response';
import { apiBodyAuthDbLoginAuthLoginPost } from '../../models/api-body-auth-db-login-auth-login-post';

export interface AuthDbLoginAuthLoginPost$Params {
      body: apiBodyAuthDbLoginAuthLoginPost
}

export function authDbLoginAuthLoginPost(http: HttpClient, rootUrl: string, params: AuthDbLoginAuthLoginPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiBearerResponse>> {
  const rb = new RequestBuilder(rootUrl, authDbLoginAuthLoginPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiBearerResponse>;
    })
  );
}

authDbLoginAuthLoginPost.PATH = '/auth/login';
