/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiUserRead } from '../../models/api-user-read';

export interface GetUsersAuthUsersGet$Params {
}

export function getUsersAuthUsersGet(http: HttpClient, rootUrl: string, params?: GetUsersAuthUsersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiUserRead>>> {
  const rb = new RequestBuilder(rootUrl, getUsersAuthUsersGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiUserRead>>;
    })
  );
}

getUsersAuthUsersGet.PATH = '/auth/users';
