/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiBodyResetResetPasswordAuthResetPasswordPost } from '../../models/api-body-reset-reset-password-auth-reset-password-post';

export interface ResetResetPasswordAuthResetPasswordPost$Params {
      body: apiBodyResetResetPasswordAuthResetPasswordPost
}

export function resetResetPasswordAuthResetPasswordPost(http: HttpClient, rootUrl: string, params: ResetResetPasswordAuthResetPasswordPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, resetResetPasswordAuthResetPasswordPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

resetResetPasswordAuthResetPasswordPost.PATH = '/auth/reset-password';
