/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiUserRead } from '../../models/api-user-read';
import { apiUserUpdate } from '../../models/api-user-update';

export interface UsersPatchUserAuthIdPatch$Params {
  id: string;
      body: apiUserUpdate
}

export function usersPatchUserAuthIdPatch(http: HttpClient, rootUrl: string, params: UsersPatchUserAuthIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiUserRead>> {
  const rb = new RequestBuilder(rootUrl, usersPatchUserAuthIdPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiUserRead>;
    })
  );
}

usersPatchUserAuthIdPatch.PATH = '/auth/{id}';
