/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiBodyVerifyVerifyAuthVerifyPost } from '../../models/api-body-verify-verify-auth-verify-post';
import { apiUserRead } from '../../models/api-user-read';

export interface VerifyVerifyAuthVerifyPost$Params {
      body: apiBodyVerifyVerifyAuthVerifyPost
}

export function verifyVerifyAuthVerifyPost(http: HttpClient, rootUrl: string, params: VerifyVerifyAuthVerifyPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiUserRead>> {
  const rb = new RequestBuilder(rootUrl, verifyVerifyAuthVerifyPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiUserRead>;
    })
  );
}

verifyVerifyAuthVerifyPost.PATH = '/auth/verify';
