/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiBodyVerifyRequestTokenAuthRequestVerifyTokenPost } from '../../models/api-body-verify-request-token-auth-request-verify-token-post';

export interface VerifyRequestTokenAuthRequestVerifyTokenPost$Params {
      body: apiBodyVerifyRequestTokenAuthRequestVerifyTokenPost
}

export function verifyRequestTokenAuthRequestVerifyTokenPost(http: HttpClient, rootUrl: string, params: VerifyRequestTokenAuthRequestVerifyTokenPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, verifyRequestTokenAuthRequestVerifyTokenPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

verifyRequestTokenAuthRequestVerifyTokenPost.PATH = '/auth/request-verify-token';
