type ScoreType = 'Reps' | 'Weight' | 'Time' | 'Tiebreak';

export interface AppConfig {
  eventName: string;
  categories: string[];
  athletesPerTeam: number;
  wods: WodConfig[];
  wodsUrl?: string;
  standardsUrl?: string;
}

export interface WodConfig {
  wodNumber: number;
  wodName: string;
  wodSummary: string;
  wodDescription?: string[];
  categoryWodDescription?: Record<string, string[]>;
  scoreTypes: ScoreType[];
}

export const appConfig: { [key: string]: AppConfig } = {
  dtpairs2025: {
    eventName: 'Deccan Throwdown Pairs 2025',
    categories: [
      'FF-Beginners',
      'MF-Beginners',
      'MM-Beginners',
      'FF-Open',
      'MF-Open',
      'MM-Open',
    ],
    athletesPerTeam: 2,
    wods: [
      {
        wodNumber: 1,
        wodName: 'Head, Shoulders, Knees & Toes',
        wodSummary: 'AMRAP 15 mins Pullups, Toes-to-bar, Shoulder-to-overheads',
        wodDescription: [
          'Open: 2 Pull-ups, 5 Toes-to-bar, 7 Shoulder-to-overheads  (♀25kg ♂40kg)',
          'Beginner: 4 Jumping Pull-Ups, 5 Hanging Knee Raises, 7 Shoulder-to-Overheads (♀15kg ♂25kg)',
        ],
        scoreTypes: ['Reps'],
      },
      {
        wodNumber: 2,
        wodName: 'काका ! मला वाचवा !',
        wodSummary: 'For Time: 100m Run, 100m Sled Pull, 100m Run',
        wodDescription: [
          'Load on the sled:',
          'Open: ⚢ 30kg ⚤ 40kg ⚣ 50kg',
          'Beginners: ⚢ 20kg ⚤ 30kg ⚣ 40kg',
        ],
        scoreTypes: ['Time'],
      },
      {
        wodNumber: 3,
        wodName: 'Love Boat',
        wodSummary: 'For Time: Dumbbell Lunges, Row, Support Hold',
        wodDescription: [
          'For Time (Time cap 12 mins):',
          '30 Alternating Synchronised Dumbbell Front Rack Lunges',
          'Calorie Row / Support Hold / High Plank',
          '30 Alternating Synchronised Dumbbell Front Rack Lunges',
          'DB weights: Open: ♀ 10kg ♂15kg; Beginners: ♀ 5kg ♂7.5kg',
          'Row cals: Open: ⚢ 50 ⚤ 60 ⚣ 75; Beginners: ⚢ 40 ⚤ 50 ⚣ 60',
          'During row cals: Open: Parallel Bar Support Hold; Beginners: High Plank',
        ],
        scoreTypes: ['Reps', 'Time'],
      },
      {
        wodNumber: 4,
        wodName: 'Heavy Triple',
        wodSummary: '5 mins to establish a Max. 3-Rep Hang Clean',
        wodDescription: [],
        scoreTypes: ['Weight'],
      },
    ],
    standardsUrl: 'assets/standards/dtpairs2025-standards.pdf',
  },
  dtteams2025: {
    eventName: 'Deccan Throwdown Teams 2025',
    categories: ['Open', 'Intermediate', 'Beginner'],
    athletesPerTeam: 4,
    wods: [
      {
        wodNumber: 1,
        wodName: "Drop it like it's hot",
        wodSummary: 'Lots of Squats for time',
        categoryWodDescription: {
          Open: [
            'For Time in F/F and M/M pairs:',
            '30 Overhead Squats @ weight 1',
            '20 Overhead Squats @ weight 2',
            '10 Overhead Squats @ weight 3',
            '♀ 25,35,45 kg & ♂ 40,50,60 kg',
            'Time Cap: 5 mins',
            '',
            'Score is Time taken by both pairs to complete the workout OR Total Repetitions completed for both pairs at time cap',
            'If only one pair completes the workout, their completion time will be recorded as tie break',
            '',
            '* Both pairs will be working at the same time but independently and DO NOT need to be in sync',
            '* Both pairs can switch the working athlete at any time and there is no minimum work requirement for any team mate',
            '* Teammates can help in changing the weights on the barbell',
          ],
          Intermediate: [
            'For Time in F/F and M/M pairs:',
            '30 Overhead Squats @ weight 1',
            '20 Overhead Squats @ weight 2',
            '10 Overhead Squats @ weight 3',
            '♀ 20,25,30 kg & ♂ 30,40,50 kg',
            'Time Cap: 5 mins',
            '',
            'Score is Time taken by both pairs to complete the workout OR Total Repetitions completed for both pairs at time cap',
            'If only one pair completes the workout, their completion time will be recorded as tie break',
            '',
            '* Both pairs will be working at the same time but independently and DO NOT need to be in sync',
            '* Both pairs can switch the working athlete at any time and there is no minimum work requirement for any team mate',
            '* Teammates can help in changing the weights on the barbell',
          ],
          Beginner: [
            'For Time in F/F and M/M pairs:',
            '30 Front Squats @ weight 1',
            '20 Front Squats @ weight 2',
            '10 Front Squats @ weight 3',
            '♀ 15,20,25 kg & ♂ 20,30,40 kg',
            'Time Cap: 5 mins',
            '',
            'Score is Time taken by both pairs to complete the workout OR Total Repetitions completed for both pairs at time cap',
            'If only one pair completes the workout, their completion time will be recorded as tie break',
            '',
            '* Both pairs will be working at the same time but independently and DO NOT need to be in sync',
            '* Both pairs can switch the working athlete at any time and there is no minimum work requirement for any team mate',
            '* Teammates can help in changing the weights on the barbell',
          ],
        },
        scoreTypes: ['Reps', 'Time', 'Tiebreak'],
      },
      {
        wodNumber: 2,
        wodName: 'Beam me up, Scotty',
        wodSummary: 'AMREPS: Row, Pull-ups, Bike, Push-ups and rope climbs',
        categoryWodDescription: {
          Open: [
            'In 15 Minutes, complete as many Repetitions as possible of: ',
            '80 Calorie Row',
            '50 Pull-Ups',
            '80 Calorie Air Bike',
            '50 Ring Push-Ups ',
            'Max Legless Rope Climb from seated (8ft)',
            'Only one teammate can accumulate repetitions at a time',
            'Non-working teammates - 100 kg (50+50) Double Barbell Hold',
            '',
            'The score is the number of Repetitions completed at the 15 minute mark',
            'The time at the completion of push ups will be noted for tie breaks',
            '',
            '* Teams can switch working the athlete at any time, there is no minimum work requirement for any team mate',
            '* Any number of teammates may be holding the barbells',
            '* BOTH barbells MUST be off the floor for the repetitions of the working teammate to count. If any of the barbells touch the floor, the working teammate MUST stop',
          ],
          Intermediate: [
            'In 15 Minutes complete as many Repetitions as possible of: ',
            '65 Calorie Row',
            '35 Pull-Ups',
            '65 Calorie Air Bike',
            '35 Hand Release Push-Ups',
            'Max Legless Rope Pull-Ups from seated',
            'Only one teammate can accumulate repetitions at a time',
            'Non-working teammates - 80 kg (40+40) Double Barbell Hold',
            '',
            'The score is the number of Repetitions completed at the 15 minute mark',
            'The time at the completion of push ups will be noted for tie breaks',
            '',
            '* Teams can switch working the athlete at any time, there is no minimum work requirement for any team mate',
            '* Any number of teammates may be holding the barbells',
            '* BOTH barbells MUST be off the floor for the repetitions of the working teammate to count. If any of the barbells touch the floor, the working teammate MUST stop',
          ],
          Beginner: [
            'In 15 Minutes complete as many Repetitions as possible of: ',
            '50 Calorie Row',
            '50 DB Renegade Rows @ 10kg',
            '50 Calorie Air Bike',
            '35 Hand Release Push-Ups from the Knees',
            'Max Lying to Standing Rope Climbs',
            'Only one teammate can accumulate repetitions at a time',
            'Non-working teammates - 60 kg (30+30) Double Barbell Hold',
            '',
            'The score is the number of Repetitions completed at the 15 minute mark',
            'The time at the completion of push ups will be noted for tie breaks',
            '',
            '* Teams can switch working the athlete at any time, there is no minimum work requirement for any team mate',
            '* Any number of teammates may be holding the barbells',
            '* BOTH barbells MUST be off the floor for the repetitions of the working teammate to count. If any of the barbells touch the floor, the working teammate MUST stop',
          ],
        },
        scoreTypes: ['Reps', 'Tiebreak'],
      },
      {
        wodNumber: 3,
        wodName: 'Sympathy for the Devil',
        wodSummary: "FT: Devil's Press, Shuttle runs and Double Unders",
        categoryWodDescription: {
          Open: [
            'For Time:',
            "In a F/M Pair, 80 Synchro Single Arm Dumbbell Devil's Press @ ♀ 15 kg / ♂ 20 kg",
            'Buy-In:',
            'Every 3:00, including 0:00',
            'Athlete 1, Athlete 2 - 14 Alternating Shuttle Runs (1 Shuttle Run = 25ft out and back)',
            'Athlete 3, Athlete 4 - Accumulate 100 Double Unders',
            'Time Cap: 21 Minutes',
            '',
            'Score is Total Time taken OR Total Repetitions completed at time cap',
            '',
            "* The ENTIRE TEAM MUST complete BOTH Buy-Ins (Shuttle Runs and Double Unders) every 3:00 BEFORE a F/M Pair starts the Devil's Presses.",
            '* The Shuttle Runs MUST be completed with both Athlete 1 and Athlete 2 alternating the runs. 1 Shuttle Run = 25ft out and back',
            '* The Double Unders may be split anyhow between Athlete 3 and Athlete 4, only one athlete working at a time',
            '* Teammates may switch between Shuttle Runs and Double Unders ONLY AFTER a 3-minute round is complete',
            "* A F/M Pair MUST perform the devil's press in sync. Working teammates on the devil's press may switch at any time, as long as it remains a F/M pair.",
            '* There is no minimum work requirement on any teammate, except the alternating shuttle run rule.',
          ],
          Intermediate: [
            'For Time:',
            "In a F/M Pair, 80 Synchro Single Arm Dumbbell Devil's Press @ ♀ 10 kg / ♂ 15 kg",
            'Buy-In:',
            'Every 3:00, including 0:00',
            'Athlete 1, Athlete 2 - 10 Alternating Shuttle Runs (1 Shuttle Run = 25ft out and back)',
            'Athlete 3, Athlete 4 - Accumulate 75 Double Unders',
            'Athletes can change stations as they want after each 3:00 round',
            'Time Cap: 21 Minutes',
            '',
            'Score is Total Time taken OR Total Repetitions completed at time cap',
            '',
            "* The ENTIRE TEAM MUST complete BOTH Buy-Ins (Shuttle Runs and Double Unders) every 3:00 BEFORE a F/M Pair starts the Devil's Presses.",
            '* The Shuttle Runs MUST be completed with both Athlete 1 and Athlete 2 alternating the runs. 1 Shuttle Run = 25ft out and back',
            '* The Double Unders may be split anyhow between Athlete 3 and Athlete 4, only one athlete working at a time',
            '* Teammates may switch between Shuttle Runs and Double Unders ONLY AFTER a 3-minute round is complete',
            "* A F/M Pair MUST perform the devil's press in sync. Working teammates on the devil's press may switch at any time, as long as it remains a F/M pair.",
            '* There is no minimum work requirement on any teammate, except the alternating shuttle run rule.',
          ],
          Beginner: [
            'For Time:',
            "In a F/M Pair, 60 Synchro Single Arm Dumbbell Devil's Press @ ♀ 7.5 kg / ♂ 10 kg",
            'Buy-In:',
            'Every 3:00, including 0:00',
            'Athlete 1, Athlete 2 - 8 Alternating Shuttle Runs (1 Shuttle Run = 25ft out and back)',
            'Athlete 3, Athlete 4 - Accumulate 150 Single Unders',
            'Athletes can change stations as they want after each 3:00 round',
            'Time Cap: 21 Minutes',
            '',
            'Score is Total Time taken OR Total Repetitions completed at time cap',
            '',
            "* The ENTIRE TEAM MUST complete BOTH Buy-Ins (Shuttle Runs and Single Unders) every 3:00 BEFORE a F/M Pair starts the Devil's Presses.",
            '* The Shuttle Runs MUST be completed with both Athlete 1 and Athlete 2 alternating the runs. 1 Shuttle Run = 25ft out and back',
            '* The Single Unders may be split anyhow between Athlete 3 and Athlete 4, only one athlete working at a time',
            '* Teammates may switch between Shuttle Runs and Single Unders ONLY AFTER a 3-minute round is complete',
            "* A F/M Pair MUST perform the devil's press in sync. Working teammates on the devil's press may switch at any time, as long as it remains a F/M pair.",
            '* There is no minimum work requirement on any teammate, except the alternating shuttle run rule.',
          ],
        },
        scoreTypes: ['Time', 'Reps'],
      },
      {
        wodNumber: 4,
        wodName: 'From the window to the wall',
        wodSummary: 'FT: Wall walks, Box jump overs, Cleans',
        categoryWodDescription: {
          Open: [
            'As a Team complete the following For Time: ',
            '9-7-5',
            'Wall-Walks ',
            'Box Jump Overs @ ♀ 20" / ♂ 24”',
            '(All teammates complete each repetition consecutively)',
            'Cleans @ ♀ 45kg / ♂ 70kg',
            'Time cap: 12 Minutes',
            '',
            'Score is Total Time taken OR Total Repetitions completed at time cap',
            '',
            '* ONLY ONE teammate works at one time on the Wall Walks and the Cleans, i.e. ONLY ONE barbell MUST be in play',
            '* The repetitions may be split between Male and Female teammates. There is no minimum work requirement for any one teammate on the wall walks or the cleans',
            '* ALL teammates MUST complete each repetition of the Box Jump Over one after the other for a repetition to count (9 each , then 7 each and then 5 each )',
          ],
          Intermediate: [
            'As a Team complete the following For Time: ',
            '9-7-5',
            'Partial Wall-Walks ',
            'Box Jump Overs @ ♀ 20" / ♂ 20”',
            '(All teammates complete each repetition consecutively)',
            'Cleans @ ♀ 35kg / ♂ 50kg',
            'Time cap: 12 Minutes',
            '',
            'Score is Total Time taken OR Total Repetitions completed at time cap',
            '',
            '* ONLY ONE teammate works at one time on the Wall Walks and the Cleans, i.e. ONLY ONE barbell MUST be in play',
            '* The repetitions may be split between Male and Female teammates. There is no minimum work requirement for any one teammate on the wall walks or the cleans',
            '* ALL teammates MUST complete each repetition of the Box Jump Over one after the other for a repetition to count (9 each , then 7 each and then 5 each )',
          ],
          Beginner: [
            'As a Team complete the following For Time: ',
            '9-7-5',
            '10ft Bear Crawls (10ft = 1 rep)',
            'Box Step Overs @ ♀ 20" / ♂ 20”',
            '(All teammates complete each repetition consecutively)',
            'Cleans @ ♀ 25kg / ♂ 35kg',
            'Time cap: 12 Minutes',
            '',
            'Score is Total Time taken OR Total Repetitions completed at time cap',
            '',
            '* ONLY ONE teammate works at one time on the Bear Crawls and the Cleans, i.e. ONLY ONE barbell MUST be in play',
            '* The repetitions may be split between Male and Female teammates. There is no minimum work requirement for any one teammate on the bear crawls or the cleans',
            '* ALL teammates MUST complete each repetition of the Box Step Over one after the other for a repetition to count (9 each , then 7 each and then 5 each )',
          ],
        },
        scoreTypes: ['Time'],
      },
    ],
    wodsUrl: 'assets/standards/dtteams2025-wods.pdf',
  },
};

export const defaultConfig = 'dtteams2025';
