services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/database.db:/app/database.db

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/www:/usr/share/nginx/html
      - ./nginx/nginx-initial.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
