/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiWodCreateModel } from '../../models/api-wod-create-model';
import { apiWodOutputModel } from '../../models/api-wod-output-model';

export interface CreateWodWodsPost$Params {
      body: apiWodCreateModel
}

export function createWodWodsPost(http: HttpClient, rootUrl: string, params: CreateWodWodsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiWodOutputModel>> {
  const rb = new RequestBuilder(rootUrl, createWodWodsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiWodOutputModel>;
    })
  );
}

createWodWodsPost.PATH = '/wods/';
