/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiWodsOutputModel } from '../../models/api-wods-output-model';

export interface GetWodsWodsGet$Params {
  event_short_name: string;
  wod_number?: (number | null);
}

export function getWodsWodsGet(http: HttpClient, rootUrl: string, params: GetWodsWodsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiWodsOutputModel>>> {
  const rb = new RequestBuilder(rootUrl, getWodsWodsGet.PATH, 'get');
  if (params) {
    rb.query('event_short_name', params.event_short_name, {});
    rb.query('wod_number', params.wod_number, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiWodsOutputModel>>;
    })
  );
}

getWodsWodsGet.PATH = '/wods/';
