/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiWodsOutputModel } from '../../models/api-wods-output-model';

export interface GetWodWodsWodIdGet$Params {
  wod_id: string;
}

export function getWodWodsWodIdGet(http: HttpClient, rootUrl: string, params: GetWodWodsWodIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiWodsOutputModel>> {
  const rb = new RequestBuilder(rootUrl, getWodWodsWodIdGet.PATH, 'get');
  if (params) {
    rb.path('wod_id', params.wod_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiWodsOutputModel>;
    })
  );
}

getWodWodsWodIdGet.PATH = '/wods/{wod_id}';
