/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiWodOutputModel } from '../../models/api-wod-output-model';
import { apiWodUpdateModel } from '../../models/api-wod-update-model';

export interface UpdateWodWodsWodIdPatch$Params {
  wod_id: string;
      body: apiWodUpdateModel
}

export function updateWodWodsWodIdPatch(http: HttpClient, rootUrl: string, params: UpdateWodWodsWodIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiWodOutputModel>> {
  const rb = new RequestBuilder(rootUrl, updateWodWodsWodIdPatch.PATH, 'patch');
  if (params) {
    rb.path('wod_id', params.wod_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiWodOutputModel>;
    })
  );
}

updateWodWodsWodIdPatch.PATH = '/wods/{wod_id}';
