/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { apiAthleteRegistrationModel } from '../models/api-athlete-registration-model';
export interface apiTeamRegistrationModel {
  athletes: Array<apiAthleteRegistrationModel>;
  category: string;
  event_short_name: string;
  team_name: string;
}
