/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiEventsUpdateModel {
  athletes_per_team?: (number | null);
  city?: (string | null);
  country?: (string | null);
  end_date?: (string | null);
  event_name?: (string | null);
  event_short_name?: (string | null);
  organization_name?: (string | null);
  start_date?: (string | null);
  year?: (number | null);
}
