/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAthleteCreateModel {
  city?: (string | null);
  email?: (string | null);
  first_name: string;
  gym?: (string | null);
  last_name: string;
  phone_number?: (string | null);
  sex: 'M' | 'F';
  team_id: string;
  waiver?: boolean;
}
