/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAthleteRegistrationModel {
  city?: (string | null);
  email?: (string | null);
  first_name: string;
  gym?: (string | null);
  last_name: string;
  sex: 'M' | 'F';
  waiver?: boolean;
}
