/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiScoreOutputModel {
  id: string;
  reps?: (number | null);
  score_detail?: (string | null);
  team_id: string;
  tiebreak_s?: (number | null);
  time_s?: (number | null);
  verified: boolean;
  wod_number: number;
  wod_rank?: (number | null);
}
