/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAthleteOutputModel {
  city?: (string | null);
  email?: (string | null);
  first_name: string;
  gym?: (string | null);
  id: string;
  last_name: string;
  sex: 'M' | 'F';
  team_id: string;
  waiver?: boolean;
}
