/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiBodyAuthDbLoginAuthLoginPost {
  client_id?: (string | null);
  client_secret?: (string | null);
  grant_type?: (string | null);
  password: string;
  scope?: string;
  username: string;
}
