/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiScoresUpdateModel {
  reps?: (number | null);
  score_detail?: ({
[key: string]: any;
} | null);
  tiebreak_s?: (number | null);
  time_s?: (number | null);
}
