/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { apiWodsOutputModelDetail } from '../models/api-wods-output-model-detail';
export interface apiEventsModelWodDetail {
  athletes_per_team: number;
  city: string;
  country: string;
  end_date: string;
  event_name: string;
  event_short_name: string;
  id: string;
  organization_name: string;
  start_date: string;
  wods: Array<apiWodsOutputModelDetail>;
  year: number;
}
