/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiScoreUpdateModel {
  reps?: (number | null);
  score_detail?: (string | null);
  tiebreak_s?: (number | null);
  time_s?: (number | null);
}
