/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAthleteUpdateModel {
  city?: (string | null);
  email?: (string | null);
  first_name?: (string | null);
  gym?: (string | null);
  last_name?: (string | null);
  sex?: (string | null);
  team_id?: (string | null);
  waiver?: (boolean | null);
}
