/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiUserCreate {
  email: string;
  is_active?: (boolean | null);
  is_superuser?: (boolean | null);
  is_verified?: (boolean | null);
  name: string;
  password: string;
}
