/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiWodsOutputModel {
  event_short_name: string;
  id: string;
  wod_description: {
[key: string]: any;
};
  wod_name: string;
  wod_number: number;
  wod_score_type: string;
}
