/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiFcmTokenRegisterModel {
  event_short_name: string;
  platform?: (string | null);
  subscribe_event?: boolean;
  token: string;
  user_agent?: (string | null);
}
