/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { apiWaiverLinkModel } from '../models/api-waiver-link-model';
export interface apiTeamRegistrationResponseModel {
  payment_link: string;
  waiver_links?: (Array<apiWaiverLinkModel> | null);
}
