/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiUserUpdate {
  email?: (string | null);
  is_active?: (boolean | null);
  is_superuser?: (boolean | null);
  is_verified?: (boolean | null);
  name?: (string | null);
  password?: (string | null);
}
