/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { apiAthleteOutputModel } from '../models/api-athlete-output-model';
import { apiScoreOutputModel } from '../models/api-score-output-model';
export interface apiTeamsOutputDetailModel {
  athletes: Array<apiAthleteOutputModel>;
  category: string;
  event_short_name: string;
  id: string;
  overall_rank?: (number | null);
  paid: boolean;
  scores: Array<apiScoreOutputModel>;
  team_name: string;
  verified: boolean;
}
