/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiWodsUpdateModel {
  event_short_name?: (string | null);
  wod_description?: ({
[key: string]: any;
} | null);
  wod_name?: (string | null);
  wod_number?: (number | null);
  wod_score_type?: (string | null);
}
