/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiTeamsCreateModel {
  category: string;
  event_short_name: string;
  paid?: boolean;
  team_name: string;
  verified?: boolean;
}
