/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { apiScoreOutputModel } from '../models/api-score-output-model';
export interface apiWodOutputModelDetail {
  event_short_name: string;
  id: string;
  scores: Array<apiScoreOutputModel>;
  wod_description?: (string | null);
  wod_name: string;
  wod_number: number;
  wod_score_type: string;
}
