/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAthleteCreateModel {
  city?: (string | null);
  email: string;
  first_name: string;
  gym?: (string | null);
  last_name: string;
  sex: string;
  team_id: string;
  waiver?: boolean;
}
