/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiTeamsUpdateModel {
  category?: (string | null);
  event_short_name?: (string | null);
  paid?: (boolean | null);
  team_name?: (string | null);
  verified?: (boolean | null);
}
