/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { apiTeamsOutputDetailModel } from '../models/api-teams-output-detail-model';
export interface apiEventsModelTeamDetail {
  athletes_per_team: number;
  city: string;
  country: string;
  end_date: string;
  event_name: string;
  event_short_name: string;
  id: string;
  organization_name: string;
  start_date: string;
  teams: Array<apiTeamsOutputDetailModel>;
  year: number;
}
