/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiScoresCreateModel {
  reps?: (number | null);
  score_detail: {
[key: string]: any;
};
  team_id: string;
  tiebreak_s?: (number | null);
  time_s?: (number | null);
  wod_id: string;
}
