/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiEventsModel {
  athletes_per_team: number;
  city?: (string | null);
  country?: (string | null);
  end_date?: (string | null);
  event_name: string;
  event_short_name: string;
  id: string;
  organization_name?: (string | null);
  start_date?: (string | null);
  year: number;
}
