/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiScoreCreateModel {
  reps?: number;
  score_detail?: (string | null);
  team_id: string;
  tiebreak_s?: (number | null);
  time_s?: (number | null);
  wod_id: string;
}
