/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiWodUpdateModel {
  event_short_name?: (string | null);
  wod_description?: (string | null);
  wod_name?: (string | null);
  wod_number?: (number | null);
  wod_score_type?: (string | null);
}
