/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiCustomNotificationSendModel {
  body: string;
  event_short_name: string;
  route?: string;
  title: string;
}
