/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiTeamsOutputModel {
  category: string;
  event_short_name: string;
  id: string;
  overall_rank?: (number | null);
  paid: boolean;
  team_name: string;
  verified: boolean;
}
