/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiEventsCreateModel {
  athletes_per_team: number;
  city: string;
  country: string;
  end_date: string;
  event_name: string;
  event_short_name: string;
  organization_name: string;
  start_date: string;
  year: number;
}
