/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { apiTeamsOutputDetailModel } from '../models/api-teams-output-detail-model';
export interface apiEventsModelTeamDetail {
  athletes_per_team: number;
  city?: (string | null);
  country?: (string | null);
  end_date?: (string | null);
  event_name: string;
  event_short_name: string;
  id: string;
  organization_name?: (string | null);
  start_date?: (string | null);
  teams: Array<apiTeamsOutputDetailModel>;
  year: number;
}
