/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { apiValidationError } from '../models/api-validation-error';
export interface apiHttpValidationError {
  detail?: Array<apiValidationError>;
}
