/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { apiScoresOutputModel } from '../models/api-scores-output-model';
export interface apiWodsOutputModelDetail {
  event_short_name: string;
  id: string;
  scores: Array<apiScoresOutputModel>;
  wod_description: {
[key: string]: any;
};
  wod_name: string;
  wod_number: number;
  wod_score_type: string;
}
