/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { apiFirebaseCustomClaims } from '../models/api-firebase-custom-claims';
export interface apiFirebaseUserRecord {
  custom_claims: (apiFirebaseCustomClaims | null);
  disabled: boolean;
  display_name: (string | null);
  email: (string | null);
  email_verified: boolean;
  photo_url: (string | null);
  provider_id: string;
  tenant_id: (string | null);
  uid: string;
}
