/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiFcmTokenRegisterModel } from '../../models/api-fcm-token-register-model';
import { apiFcmTokenRegisterResponseModel } from '../../models/api-fcm-token-register-response-model';

export interface RegisterFcmTokenNotificationsTokensPost$Params {
      body: apiFcmTokenRegisterModel
}

export function registerFcmTokenNotificationsTokensPost(http: HttpClient, rootUrl: string, params: RegisterFcmTokenNotificationsTokensPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiFcmTokenRegisterResponseModel>> {
  const rb = new RequestBuilder(rootUrl, registerFcmTokenNotificationsTokensPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiFcmTokenRegisterResponseModel>;
    })
  );
}

registerFcmTokenNotificationsTokensPost.PATH = '/notifications/tokens';
