/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiScoresCreateModel } from '../../models/api-scores-create-model';
import { apiScoresOutputModel } from '../../models/api-scores-output-model';

export interface CreateScoreScoresPost$Params {
      body: apiScoresCreateModel
}

export function createScoreScoresPost(http: HttpClient, rootUrl: string, params: CreateScoreScoresPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiScoresOutputModel>> {
  const rb = new RequestBuilder(rootUrl, createScoreScoresPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiScoresOutputModel>;
    })
  );
}

createScoreScoresPost.PATH = '/scores/';
