/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiScoresOutputModel } from '../../models/api-scores-output-model';

export interface GetScoresScoresGet$Params {
  team_id?: (string | null);
  wod_id?: (string | null);
}

export function getScoresScoresGet(http: HttpClient, rootUrl: string, params?: GetScoresScoresGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiScoresOutputModel>>> {
  const rb = new RequestBuilder(rootUrl, getScoresScoresGet.PATH, 'get');
  if (params) {
    rb.query('team_id', params.team_id, {});
    rb.query('wod_id', params.wod_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiScoresOutputModel>>;
    })
  );
}

getScoresScoresGet.PATH = '/scores/';
