/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiScoresOutputModel } from '../../models/api-scores-output-model';

export interface GetScoreScoresScoreIdGet$Params {
  score_id: string;
}

export function getScoreScoresScoreIdGet(http: HttpClient, rootUrl: string, params: GetScoreScoresScoreIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiScoresOutputModel>> {
  const rb = new RequestBuilder(rootUrl, getScoreScoresScoreIdGet.PATH, 'get');
  if (params) {
    rb.path('score_id', params.score_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiScoresOutputModel>;
    })
  );
}

getScoreScoresScoreIdGet.PATH = '/scores/{score_id}';
