/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UpdateEventRanksScoresUpdateRanksPut$Params {
  event_short_name: string;
  wod_number: number;
}

export function updateEventRanksScoresUpdateRanksPut(http: HttpClient, rootUrl: string, params: UpdateEventRanksScoresUpdateRanksPut$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, updateEventRanksScoresUpdateRanksPut.PATH, 'put');
  if (params) {
    rb.query('event_short_name', params.event_short_name, {});
    rb.query('wod_number', params.wod_number, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

updateEventRanksScoresUpdateRanksPut.PATH = '/scores/update-ranks';
