/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiScoreOutputModel } from '../../models/api-score-output-model';

export interface UpdateScoreVerificationScoresVerifyScoreIdPatch$Params {
  score_id: string;
  verified: boolean;
}

export function updateScoreVerificationScoresVerifyScoreIdPatch(http: HttpClient, rootUrl: string, params: UpdateScoreVerificationScoresVerifyScoreIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiScoreOutputModel>> {
  const rb = new RequestBuilder(rootUrl, updateScoreVerificationScoresVerifyScoreIdPatch.PATH, 'patch');
  if (params) {
    rb.path('score_id', params.score_id, {});
    rb.query('verified', params.verified, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiScoreOutputModel>;
    })
  );
}

updateScoreVerificationScoresVerifyScoreIdPatch.PATH = '/scores/verify/{score_id}';
