/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiScoreOutputModel } from '../../models/api-score-output-model';
import { apiScoreUpdateModel } from '../../models/api-score-update-model';

export interface UpdateScoreScoresScoreIdPatch$Params {
  score_id: string;
      body: apiScoreUpdateModel
}

export function updateScoreScoresScoreIdPatch(http: HttpClient, rootUrl: string, params: UpdateScoreScoresScoreIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiScoreOutputModel>> {
  const rb = new RequestBuilder(rootUrl, updateScoreScoresScoreIdPatch.PATH, 'patch');
  if (params) {
    rb.path('score_id', params.score_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiScoreOutputModel>;
    })
  );
}

updateScoreScoresScoreIdPatch.PATH = '/scores/{score_id}';
