/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { apiAthleteCreateModel } from './models/api-athlete-create-model';
export type { apiAthleteOutputModel } from './models/api-athlete-output-model';
export type { apiAthleteUpdateModel } from './models/api-athlete-update-model';
export type { apiCreateUser } from './models/api-create-user';
export type { apiFirebaseCustomClaims } from './models/api-firebase-custom-claims';
export type { apiFirebaseUserRecord } from './models/api-firebase-user-record';
export type { apiHttpValidationError } from './models/api-http-validation-error';
export type { apiScoreCreateModel } from './models/api-score-create-model';
export type { apiScoreOutputModel } from './models/api-score-output-model';
export type { apiScoreUpdateModel } from './models/api-score-update-model';
export type { apiTeamsCreateModel } from './models/api-teams-create-model';
export type { apiTeamsOutputDetailModel } from './models/api-teams-output-detail-model';
export type { apiTeamsOutputModel } from './models/api-teams-output-model';
export type { apiTeamsUpdateModel } from './models/api-teams-update-model';
export type { apiValidationError } from './models/api-validation-error';
