/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { apiAthleteCreateModel } from './models/api-athlete-create-model';
export type { apiAthleteOutputModel } from './models/api-athlete-output-model';
export type { apiAthleteUpdateModel } from './models/api-athlete-update-model';
export type { apiCreateUser } from './models/api-create-user';
export type { apiEventsCreateModel } from './models/api-events-create-model';
export type { apiEventsModel } from './models/api-events-model';
export type { apiEventsModelTeamDetail } from './models/api-events-model-team-detail';
export type { apiEventsModelWodDetail } from './models/api-events-model-wod-detail';
export type { apiEventsUpdateModel } from './models/api-events-update-model';
export type { apiFirebaseCustomClaims } from './models/api-firebase-custom-claims';
export type { apiFirebaseUserRecord } from './models/api-firebase-user-record';
export type { apiHttpValidationError } from './models/api-http-validation-error';
export type { apiScoreCreateModel } from './models/api-score-create-model';
export type { apiScoreOutputModel } from './models/api-score-output-model';
export type { apiScoreUpdateModel } from './models/api-score-update-model';
export type { apiTeamsCreateModel } from './models/api-teams-create-model';
export type { apiTeamsOutputDetailModel } from './models/api-teams-output-detail-model';
export type { apiTeamsOutputModel } from './models/api-teams-output-model';
export type { apiTeamsUpdateModel } from './models/api-teams-update-model';
export type { apiValidationError } from './models/api-validation-error';
export type { apiWodCreateModel } from './models/api-wod-create-model';
export type { apiWodOutputModel } from './models/api-wod-output-model';
export type { apiWodOutputModelDetail } from './models/api-wod-output-model-detail';
export type { apiWodUpdateModel } from './models/api-wod-update-model';
