/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { apiAthleteCreateModel } from './models/api-athlete-create-model';
export type { apiAthleteOutputModel } from './models/api-athlete-output-model';
export type { apiAthleteUpdateModel } from './models/api-athlete-update-model';
export type { apiBearerResponse } from './models/api-bearer-response';
export type { apiBodyAuthDbLoginAuthLoginPost } from './models/api-body-auth-db-login-auth-login-post';
export type { apiBodyResetForgotPasswordAuthForgotPasswordPost } from './models/api-body-reset-forgot-password-auth-forgot-password-post';
export type { apiBodyResetResetPasswordAuthResetPasswordPost } from './models/api-body-reset-reset-password-auth-reset-password-post';
export type { apiBodyVerifyRequestTokenAuthRequestVerifyTokenPost } from './models/api-body-verify-request-token-auth-request-verify-token-post';
export type { apiBodyVerifyVerifyAuthVerifyPost } from './models/api-body-verify-verify-auth-verify-post';
export type { apiErrorModel } from './models/api-error-model';
export type { apiHttpValidationError } from './models/api-http-validation-error';
export type { apiScoreCreateModel } from './models/api-score-create-model';
export type { apiScoreOutputModel } from './models/api-score-output-model';
export type { apiScoreUpdateModel } from './models/api-score-update-model';
export type { apiTeamsCreateModel } from './models/api-teams-create-model';
export type { apiTeamsOutputDetailModel } from './models/api-teams-output-detail-model';
export type { apiTeamsOutputModel } from './models/api-teams-output-model';
export type { apiTeamsUpdateModel } from './models/api-teams-update-model';
export type { apiUserCreate } from './models/api-user-create';
export type { apiUserRead } from './models/api-user-read';
export type { apiUserUpdate } from './models/api-user-update';
export type { apiValidationError } from './models/api-validation-error';
