/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { apiAuthService } from './services/api-auth.service';
export { apiAthletesService } from './services/api-athletes.service';
export { apiTeamsService } from './services/api-teams.service';
export { apiScoresService } from './services/api-scores.service';
