/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTeamTeamsPost } from '../fn/teams/create-team-teams-post';
import { CreateTeamTeamsPost$Params } from '../fn/teams/create-team-teams-post';
import { deleteTeamTeamsTeamIdDelete } from '../fn/teams/delete-team-teams-team-id-delete';
import { DeleteTeamTeamsTeamIdDelete$Params } from '../fn/teams/delete-team-teams-team-id-delete';
import { getTeamEmailsTeamsEmailsGet } from '../fn/teams/get-team-emails-teams-emails-get';
import { GetTeamEmailsTeamsEmailsGet$Params } from '../fn/teams/get-team-emails-teams-emails-get';
import { getTeamInfoTeamsTeamIdGet } from '../fn/teams/get-team-info-teams-team-id-get';
import { GetTeamInfoTeamsTeamIdGet$Params } from '../fn/teams/get-team-info-teams-team-id-get';
import { getTeamsTeamsGet } from '../fn/teams/get-teams-teams-get';
import { GetTeamsTeamsGet$Params } from '../fn/teams/get-teams-teams-get';
import { getTeamWaiverLinksTeamsWaiverLinksGet } from '../fn/teams/get-team-waiver-links-teams-waiver-links-get';
import { GetTeamWaiverLinksTeamsWaiverLinksGet$Params } from '../fn/teams/get-team-waiver-links-teams-waiver-links-get';
import { registerTeamTeamsRegisterPost } from '../fn/teams/register-team-teams-register-post';
import { RegisterTeamTeamsRegisterPost$Params } from '../fn/teams/register-team-teams-register-post';
import { apiTeamRegistrationResponseModel } from '../models/api-team-registration-response-model';
import { apiTeamsOutputDetailModel } from '../models/api-teams-output-detail-model';
import { apiTeamsOutputModel } from '../models/api-teams-output-model';
import { updateTeamTeamsTeamIdPatch } from '../fn/teams/update-team-teams-team-id-patch';
import { UpdateTeamTeamsTeamIdPatch$Params } from '../fn/teams/update-team-teams-team-id-patch';
import { apiWaiverLinkModel } from '../models/api-waiver-link-model';

@Injectable({ providedIn: 'root' })
export class apiTeamsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTeamsTeamsGet()` */
  static readonly GetTeamsTeamsGetPath = '/teams/';

  /**
   * Get Teams.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTeamsTeamsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTeamsTeamsGet$Response(params: GetTeamsTeamsGet$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<apiTeamsOutputDetailModel>>> {
    const obs = getTeamsTeamsGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get Teams.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTeamsTeamsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTeamsTeamsGet(params: GetTeamsTeamsGet$Params, context?: HttpContext): Promise<Array<apiTeamsOutputDetailModel>> {
    const resp = this.getTeamsTeamsGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<apiTeamsOutputDetailModel>>): Array<apiTeamsOutputDetailModel> => r.body);
  }

  /** Path part for operation `createTeamTeamsPost()` */
  static readonly CreateTeamTeamsPostPath = '/teams/';

  /**
   * Create Team.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTeamTeamsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTeamTeamsPost$Response(params: CreateTeamTeamsPost$Params, context?: HttpContext): Promise<StrictHttpResponse<apiTeamsOutputModel>> {
    const obs = createTeamTeamsPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create Team.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTeamTeamsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTeamTeamsPost(params: CreateTeamTeamsPost$Params, context?: HttpContext): Promise<apiTeamsOutputModel> {
    const resp = this.createTeamTeamsPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<apiTeamsOutputModel>): apiTeamsOutputModel => r.body);
  }

  /** Path part for operation `getTeamEmailsTeamsEmailsGet()` */
  static readonly GetTeamEmailsTeamsEmailsGetPath = '/teams/emails';

  /**
   * Get Team Emails.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTeamEmailsTeamsEmailsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTeamEmailsTeamsEmailsGet$Response(params: GetTeamEmailsTeamsEmailsGet$Params, context?: HttpContext): Promise<StrictHttpResponse<string>> {
    const obs = getTeamEmailsTeamsEmailsGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get Team Emails.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTeamEmailsTeamsEmailsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTeamEmailsTeamsEmailsGet(params: GetTeamEmailsTeamsEmailsGet$Params, context?: HttpContext): Promise<string> {
    const resp = this.getTeamEmailsTeamsEmailsGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<string>): string => r.body);
  }

  /** Path part for operation `getTeamWaiverLinksTeamsWaiverLinksGet()` */
  static readonly GetTeamWaiverLinksTeamsWaiverLinksGetPath = '/teams/waiver-links';

  /**
   * Get Team Waiver Links.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTeamWaiverLinksTeamsWaiverLinksGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTeamWaiverLinksTeamsWaiverLinksGet$Response(params: GetTeamWaiverLinksTeamsWaiverLinksGet$Params, context?: HttpContext): Promise<StrictHttpResponse<(Array<apiWaiverLinkModel> | null)>> {
    const obs = getTeamWaiverLinksTeamsWaiverLinksGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get Team Waiver Links.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTeamWaiverLinksTeamsWaiverLinksGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTeamWaiverLinksTeamsWaiverLinksGet(params: GetTeamWaiverLinksTeamsWaiverLinksGet$Params, context?: HttpContext): Promise<(Array<apiWaiverLinkModel> | null)> {
    const resp = this.getTeamWaiverLinksTeamsWaiverLinksGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<(Array<apiWaiverLinkModel> | null)>): (Array<apiWaiverLinkModel> | null) => r.body);
  }

  /** Path part for operation `getTeamInfoTeamsTeamIdGet()` */
  static readonly GetTeamInfoTeamsTeamIdGetPath = '/teams/{team_id}';

  /**
   * Get Team Info.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTeamInfoTeamsTeamIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTeamInfoTeamsTeamIdGet$Response(params: GetTeamInfoTeamsTeamIdGet$Params, context?: HttpContext): Promise<StrictHttpResponse<apiTeamsOutputDetailModel>> {
    const obs = getTeamInfoTeamsTeamIdGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get Team Info.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTeamInfoTeamsTeamIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTeamInfoTeamsTeamIdGet(params: GetTeamInfoTeamsTeamIdGet$Params, context?: HttpContext): Promise<apiTeamsOutputDetailModel> {
    const resp = this.getTeamInfoTeamsTeamIdGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<apiTeamsOutputDetailModel>): apiTeamsOutputDetailModel => r.body);
  }

  /** Path part for operation `deleteTeamTeamsTeamIdDelete()` */
  static readonly DeleteTeamTeamsTeamIdDeletePath = '/teams/{team_id}';

  /**
   * Delete Team.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTeamTeamsTeamIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTeamTeamsTeamIdDelete$Response(params: DeleteTeamTeamsTeamIdDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = deleteTeamTeamsTeamIdDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete Team.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTeamTeamsTeamIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTeamTeamsTeamIdDelete(params: DeleteTeamTeamsTeamIdDelete$Params, context?: HttpContext): Promise<any> {
    const resp = this.deleteTeamTeamsTeamIdDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `updateTeamTeamsTeamIdPatch()` */
  static readonly UpdateTeamTeamsTeamIdPatchPath = '/teams/{team_id}';

  /**
   * Update Team.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTeamTeamsTeamIdPatch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTeamTeamsTeamIdPatch$Response(params: UpdateTeamTeamsTeamIdPatch$Params, context?: HttpContext): Promise<StrictHttpResponse<apiTeamsOutputModel>> {
    const obs = updateTeamTeamsTeamIdPatch(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update Team.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTeamTeamsTeamIdPatch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTeamTeamsTeamIdPatch(params: UpdateTeamTeamsTeamIdPatch$Params, context?: HttpContext): Promise<apiTeamsOutputModel> {
    const resp = this.updateTeamTeamsTeamIdPatch$Response(params, context);
    return resp.then((r: StrictHttpResponse<apiTeamsOutputModel>): apiTeamsOutputModel => r.body);
  }

  /** Path part for operation `registerTeamTeamsRegisterPost()` */
  static readonly RegisterTeamTeamsRegisterPostPath = '/teams/register';

  /**
   * Register Team.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registerTeamTeamsRegisterPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerTeamTeamsRegisterPost$Response(params: RegisterTeamTeamsRegisterPost$Params, context?: HttpContext): Promise<StrictHttpResponse<apiTeamRegistrationResponseModel>> {
    const obs = registerTeamTeamsRegisterPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Register Team.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registerTeamTeamsRegisterPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerTeamTeamsRegisterPost(params: RegisterTeamTeamsRegisterPost$Params, context?: HttpContext): Promise<apiTeamRegistrationResponseModel> {
    const resp = this.registerTeamTeamsRegisterPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<apiTeamRegistrationResponseModel>): apiTeamRegistrationResponseModel => r.body);
  }

}
