/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCustomNotificationSendResponseModel } from '../models/api-custom-notification-send-response-model';
import { apiFcmTokenRegisterResponseModel } from '../models/api-fcm-token-register-response-model';
import { registerFcmTokenNotificationsTokensPost } from '../fn/notifications/register-fcm-token-notifications-tokens-post';
import { RegisterFcmTokenNotificationsTokensPost$Params } from '../fn/notifications/register-fcm-token-notifications-tokens-post';
import { sendCustomNotificationNotificationsCustomPost } from '../fn/notifications/send-custom-notification-notifications-custom-post';
import { SendCustomNotificationNotificationsCustomPost$Params } from '../fn/notifications/send-custom-notification-notifications-custom-post';
import { unregisterFcmTokenNotificationsTokensTokenDelete } from '../fn/notifications/unregister-fcm-token-notifications-tokens-token-delete';
import { UnregisterFcmTokenNotificationsTokensTokenDelete$Params } from '../fn/notifications/unregister-fcm-token-notifications-tokens-token-delete';

@Injectable({ providedIn: 'root' })
export class apiNotificationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registerFcmTokenNotificationsTokensPost()` */
  static readonly RegisterFcmTokenNotificationsTokensPostPath = '/notifications/tokens';

  /**
   * Register Fcm Token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registerFcmTokenNotificationsTokensPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerFcmTokenNotificationsTokensPost$Response(params: RegisterFcmTokenNotificationsTokensPost$Params, context?: HttpContext): Promise<StrictHttpResponse<apiFcmTokenRegisterResponseModel>> {
    const obs = registerFcmTokenNotificationsTokensPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Register Fcm Token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registerFcmTokenNotificationsTokensPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerFcmTokenNotificationsTokensPost(params: RegisterFcmTokenNotificationsTokensPost$Params, context?: HttpContext): Promise<apiFcmTokenRegisterResponseModel> {
    const resp = this.registerFcmTokenNotificationsTokensPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<apiFcmTokenRegisterResponseModel>): apiFcmTokenRegisterResponseModel => r.body);
  }

  /** Path part for operation `unregisterFcmTokenNotificationsTokensTokenDelete()` */
  static readonly UnregisterFcmTokenNotificationsTokensTokenDeletePath = '/notifications/tokens/{token}';

  /**
   * Unregister Fcm Token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `unregisterFcmTokenNotificationsTokensTokenDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  unregisterFcmTokenNotificationsTokensTokenDelete$Response(params: UnregisterFcmTokenNotificationsTokensTokenDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = unregisterFcmTokenNotificationsTokensTokenDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Unregister Fcm Token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `unregisterFcmTokenNotificationsTokensTokenDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  unregisterFcmTokenNotificationsTokensTokenDelete(params: UnregisterFcmTokenNotificationsTokensTokenDelete$Params, context?: HttpContext): Promise<void> {
    const resp = this.unregisterFcmTokenNotificationsTokensTokenDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `sendCustomNotificationNotificationsCustomPost()` */
  static readonly SendCustomNotificationNotificationsCustomPostPath = '/notifications/custom';

  /**
   * Send Custom Notification.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendCustomNotificationNotificationsCustomPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendCustomNotificationNotificationsCustomPost$Response(params: SendCustomNotificationNotificationsCustomPost$Params, context?: HttpContext): Promise<StrictHttpResponse<apiCustomNotificationSendResponseModel>> {
    const obs = sendCustomNotificationNotificationsCustomPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Send Custom Notification.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendCustomNotificationNotificationsCustomPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendCustomNotificationNotificationsCustomPost(params: SendCustomNotificationNotificationsCustomPost$Params, context?: HttpContext): Promise<apiCustomNotificationSendResponseModel> {
    const resp = this.sendCustomNotificationNotificationsCustomPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<apiCustomNotificationSendResponseModel>): apiCustomNotificationSendResponseModel => r.body);
  }

}
