/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiEventsCreateModel } from '../../models/api-events-create-model';
import { apiEventsModel } from '../../models/api-events-model';

export interface CreateEventEventsPost$Params {
      body: apiEventsCreateModel
}

export function createEventEventsPost(http: HttpClient, rootUrl: string, params: CreateEventEventsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiEventsModel>> {
  const rb = new RequestBuilder(rootUrl, createEventEventsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiEventsModel>;
    })
  );
}

createEventEventsPost.PATH = '/events/';
