/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiEventsModelTeamDetail } from '../../models/api-events-model-team-detail';

export interface GetEventAllTeamDataEventsTeamDataEventShortNameGet$Params {
  event_short_name: string;
}

export function getEventAllTeamDataEventsTeamDataEventShortNameGet(http: HttpClient, rootUrl: string, params: GetEventAllTeamDataEventsTeamDataEventShortNameGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiEventsModelTeamDetail>> {
  const rb = new RequestBuilder(rootUrl, getEventAllTeamDataEventsTeamDataEventShortNameGet.PATH, 'get');
  if (params) {
    rb.path('event_short_name', params.event_short_name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiEventsModelTeamDetail>;
    })
  );
}

getEventAllTeamDataEventsTeamDataEventShortNameGet.PATH = '/events/team_data/{event_short_name}';
