/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiEventsModel } from '../../models/api-events-model';

export interface GetEventsEventsGet$Params {
  year?: (number | null);
}

export function getEventsEventsGet(http: HttpClient, rootUrl: string, params?: GetEventsEventsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiEventsModel>>> {
  const rb = new RequestBuilder(rootUrl, getEventsEventsGet.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiEventsModel>>;
    })
  );
}

getEventsEventsGet.PATH = '/events/';
