/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiEventsModelWodDetail } from '../../models/api-events-model-wod-detail';

export interface GetEventAllWodDataEventsWodDataEventShortNameGet$Params {
  event_short_name: string;
}

export function getEventAllWodDataEventsWodDataEventShortNameGet(http: HttpClient, rootUrl: string, params: GetEventAllWodDataEventsWodDataEventShortNameGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiEventsModelWodDetail>> {
  const rb = new RequestBuilder(rootUrl, getEventAllWodDataEventsWodDataEventShortNameGet.PATH, 'get');
  if (params) {
    rb.path('event_short_name', params.event_short_name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiEventsModelWodDetail>;
    })
  );
}

getEventAllWodDataEventsWodDataEventShortNameGet.PATH = '/events/wod_data/{event_short_name}';
