/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiEventsModel } from '../../models/api-events-model';
import { apiEventsUpdateModel } from '../../models/api-events-update-model';

export interface UpdateEventEventsEventShortNamePatch$Params {
  event_short_name: string;
      body: apiEventsUpdateModel
}

export function updateEventEventsEventShortNamePatch(http: HttpClient, rootUrl: string, params: UpdateEventEventsEventShortNamePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiEventsModel>> {
  const rb = new RequestBuilder(rootUrl, updateEventEventsEventShortNamePatch.PATH, 'patch');
  if (params) {
    rb.path('event_short_name', params.event_short_name, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiEventsModel>;
    })
  );
}

updateEventEventsEventShortNamePatch.PATH = '/events/{event_short_name}';
