/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAthleteCreateModel } from '../../models/api-athlete-create-model';
import { apiAthleteOutputModel } from '../../models/api-athlete-output-model';

export interface CreateAthleteAthletesPost$Params {
      body: apiAthleteCreateModel
}

export function createAthleteAthletesPost(http: HttpClient, rootUrl: string, params: CreateAthleteAthletesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiAthleteOutputModel>> {
  const rb = new RequestBuilder(rootUrl, createAthleteAthletesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiAthleteOutputModel>;
    })
  );
}

createAthleteAthletesPost.PATH = '/athletes/';
