/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteAthleteAthletesAthleteIdDelete$Params {
  athlete_id: string;
}

export function deleteAthleteAthletesAthleteIdDelete(http: HttpClient, rootUrl: string, params: DeleteAthleteAthletesAthleteIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, deleteAthleteAthletesAthleteIdDelete.PATH, 'delete');
  if (params) {
    rb.path('athlete_id', params.athlete_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

deleteAthleteAthletesAthleteIdDelete.PATH = '/athletes/{athlete_id}';
