/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAthleteOutputModel } from '../../models/api-athlete-output-model';

export interface GetAthleteAthletesAthleteIdGet$Params {
  athlete_id: string;
}

export function getAthleteAthletesAthleteIdGet(http: HttpClient, rootUrl: string, params: GetAthleteAthletesAthleteIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiAthleteOutputModel>> {
  const rb = new RequestBuilder(rootUrl, getAthleteAthletesAthleteIdGet.PATH, 'get');
  if (params) {
    rb.path('athlete_id', params.athlete_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiAthleteOutputModel>;
    })
  );
}

getAthleteAthletesAthleteIdGet.PATH = '/athletes/{athlete_id}';
