/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAthleteOutputModel } from '../../models/api-athlete-output-model';
import { apiAthleteUpdateModel } from '../../models/api-athlete-update-model';

export interface UpdateAthleteAthletesAthleteIdPatch$Params {
  athlete_id: string;
      body: apiAthleteUpdateModel
}

export function updateAthleteAthletesAthleteIdPatch(http: HttpClient, rootUrl: string, params: UpdateAthleteAthletesAthleteIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiAthleteOutputModel>> {
  const rb = new RequestBuilder(rootUrl, updateAthleteAthletesAthleteIdPatch.PATH, 'patch');
  if (params) {
    rb.path('athlete_id', params.athlete_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiAthleteOutputModel>;
    })
  );
}

updateAthleteAthletesAthleteIdPatch.PATH = '/athletes/{athlete_id}';
